In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [7]:
b = np.array([12, 455, 63.3, True, "abc"])

In [9]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

-1234

In [12]:
l

[23245, 27, 546, 215]

In [14]:
a.mean()

4559.8000000000002

In [15]:
a

array([23245,    27,   546,   215, -1234])

In [16]:
l

[23245, 27, 546, 215]

In [17]:
l[1:]

[27, 546, 215]

In [18]:
l[0:2]

[23245, 27]

In [19]:
l[::2]

[23245, 546]

In [20]:
#------------------

In [21]:
a

array([23245,    27,   546,   215, -1234])

In [22]:
a[2:]

array([  546,   215, -1234])

In [23]:
a[2:4]

array([546, 215])

In [24]:
b = a[2:4]

In [25]:
b

array([546, 215])

In [26]:
b[0]

546

In [27]:
b[:]

array([546, 215])

In [28]:
b[:] = 111

In [29]:
a

array([23245,    27,   111,   111, -1234])